const $=s=>document.querySelector(s), fmt=n=>n.toLocaleString(), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), title=s=>s.replace(/(^|[\s-])\p{L}/gu,c=>c.toUpperCase());
let data,selected=new Set(),family='All notes',query='',perfumeQuery='',page=0,matches=[],counts=[],totalCounts=[],sort='popular';const size=18;
const FAVORITES_KEY='for-alex.favorites.v1';
let favorites=new Set(),favoritesView=false;
function readFavorites(raw){const saved=JSON.parse(raw||'[]');if(!Array.isArray(saved)||!saved.every(x=>typeof x==='string'))throw Error('Invalid favorites');return new Set(saved)}
function favoritesNotice(message){$('#favorite-status').textContent=message;$('#favorite-status').hidden=!message}
try{favorites=readFavorites(localStorage.getItem(FAVORITES_KEY))}catch{favoritesNotice('Saved favorites could not be loaded in this browser. You can still make a list for this visit.')}
function favoriteKey(p){const id=p.url.match(/fragrantica\.[^/]+\/.*-(\d+)\.html/);return id?'fragrantica:'+id[1]:'perfume:'+p.url+'|'+p.brand+'|'+p.name}
const heartIcon='<svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/></svg>';
function favoriteButton(p){const saved=favorites.has(p.favoriteKey);return `<button class="favorite-heart ${saved?'is-favorite':''}" data-favorite="${p.id}" aria-pressed="${saved}" aria-label="${saved?'Remove':'Add'} ${esc(p.name)} by ${esc(p.brand)} ${saved?'from':'to'} favorites" title="${saved?'Remove from':'Add to'} favorites">${heartIcon}</button>`}
function refreshFavorites(){if(!data)return;$('#favorite-count').textContent=fmt(data.perfumes.filter(p=>favorites.has(p.favoriteKey)).length);$('#favorites').setAttribute('aria-pressed',String(favoritesView));$('#back-to-all').hidden=!favoritesView;$('.layout').classList.toggle('favorites-view',favoritesView);$('.layout aside').hidden=favoritesView;$('.selection').hidden=favoritesView;document.querySelectorAll('[data-favorite]').forEach(b=>{const p=data.perfumes[Number(b.dataset.favorite)],saved=favorites.has(p.favoriteKey);b.classList.toggle('is-favorite',saved);b.setAttribute('aria-pressed',String(saved));b.setAttribute('aria-label',`${saved?'Remove':'Add'} ${p.name} by ${p.brand} ${saved?'from':'to'} favorites`);b.title=saved?'Remove from favorites':'Add to favorites'})}
function toggleFavorite(id){const p=data.perfumes[id];if(!p)return;favorites.has(p.favoriteKey)?favorites.delete(p.favoriteKey):favorites.add(p.favoriteKey);try{localStorage.setItem(FAVORITES_KEY,JSON.stringify([...favorites]));favoritesNotice('')}catch{favoritesNotice('This browser could not save your favorites. Your changes will last only for this visit.')}if(favoritesView)update();refreshFavorites()}
window.addEventListener('storage',e=>{if(e.key!==FAVORITES_KEY&&e.key!==null)return;try{favorites=readFavorites(e.newValue);if(data){if(favoritesView)update();refreshFavorites()}}catch{favoritesNotice('Favorites changed in another tab but could not be read.')}});
$('#favorites').onclick=()=>{if(!data)return;favoritesView=!favoritesView;update();refreshFavorites()};
$('#back-to-all').onclick=()=>{favoritesView=false;update();refreshFavorites()};
// Fragrantica bottle thumbnail URLs are keyed by the perfume ID in its source URL.
function bottle(p,large=false){const id=p.url.match(/-(\d+)\.html(?:$|[?#])/);const src=p.image||(id?`https://fimgs.net/mdimg/perfume-thumbs/375x500.${id[1]}.jpg`:'');if(!src)return '<span class="bottle-missing">Photo unavailable</span>';return `<span class="bottle-frame ${large?'bottle-large':''}"><img src="${esc(src)}" alt="${esc(p.name)} by ${esc(p.brand)} bottle" width="375" height="500" loading="${large?'eager':'lazy'}" decoding="async" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="bottle-missing" hidden>Photo unavailable</span></span>`}
function tag(id){return `<span class="tag ${selected.has(data.notes[id].group??id)?'match':''}">${esc(title(data.notes[id].name))}</span>`}
function update(){const terms=perfumeQuery.split(/\s+/).map(searchKey).filter(Boolean);matches=data.perfumes.filter(p=>terms.every(term=>p.searchText.includes(term))&&(favoritesView?favorites.has(p.favoriteKey):[...selected].every(id=>p.notes.includes(id))));counts=new Uint32Array(data.notes.length);for(const p of matches)for(const id of p.notes)counts[id]++;if(sort==='rating')matches.sort((a,b)=>b.rating-a.rating||b.votes-a.votes);if(sort==='name')matches.sort((a,b)=>a.name.localeCompare(b.name));page=0;renderSelected();renderNotes();renderCards()}
function renderSelected(){$('#selected').innerHTML=selected.size?[...selected].map(id=>`<button class="selected-note" data-remove="${id}" aria-label="Remove ${esc(data.notes[id].name)}">${esc(title(data.notes[id].name))}<span aria-hidden="true">×</span></button>`).join(''):'<span class="muted">No notes selected.</span>';$('#clear').hidden=!selected.size}
const searchKey=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
function visibleNote(n,id){return (n.group??id)===id&&(totalCounts[id]>2||n.name==='firewood')}
function renderNotes(){const exactQuery=query&&data.notes.some((n,id)=>(n.group??id)===id&&searchKey(n.name)===searchKey(query));const ns=data.notes.map((n,id)=>({...n,id})).filter(n=>visibleNote(n,n.id)&&(family==='All notes'||n.family===family)&&(!query||[n.name,...(exactQuery?[]:(n.aliases||[]))].some(v=>searchKey(v).includes(searchKey(query))))).sort((a,b)=>a.name.localeCompare(b.name));$('#notes').innerHTML=ns.length?ns.map(n=>`<button class="note ${selected.has(n.id)?'chosen':''}" data-note="${n.id}" aria-pressed="${selected.has(n.id)}" ${!counts[n.id]&&!selected.has(n.id)?'disabled':''}><span class="box" aria-hidden="true">${selected.has(n.id)?'✓':''}</span><span>${esc(title(n.name))}</span><span class="number">${fmt(counts[n.id])}</span></button>`).join(''):'<p class="muted">No notes found. Try another spelling.</p>';$('#note-list-count').textContent=fmt(ns.length)+(ns.length===1?' note':' notes');$('#family-label').textContent=query?'SEARCH RESULTS':family==='All notes'?'ALL NOTES':family.toUpperCase()}
function sampleLinks(p){const q=encodeURIComponent(p.brand+' '+p.name);return `<a href="${esc(p.luckyUrl||`https://www.luckyscent.com/search?term=${q}`)}" target="_blank" rel="noopener noreferrer" aria-label="${p.luckyUrl?'View':'Search'} Luckyscent for ${esc(p.name)} by ${esc(p.brand)} samples">Luckyscent</a><details class="sample-fallback"><summary>${p.luckyUrl?'Other sample options':'Not on Luckyscent?'}</summary><a href="https://www.scentsplit.com/search?q=${q}&amp;type=product" target="_blank" rel="noopener noreferrer" aria-label="Search Scent Split for ${esc(p.name)} by ${esc(p.brand)} samples">Try Scent Split</a></details>`}

function reviewLink(p,label){const source=p.url.includes('luckyscent.com')?'Luckyscent':p.url.includes('fragrantica.')?'Fragrantica':'the source site';return `<a class="review-link" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer" aria-label="Read ratings and reviews for ${esc(p.name)} by ${esc(p.brand)} on ${source}">${label}</a>`}
function renderCards(){$('#count').textContent=fmt(matches.length);$('#result-noun').textContent=favoritesView?(matches.length===1?'favorite':'favorites'):(matches.length===1?'perfume':'perfumes');$('#result-caption').textContent=perfumeQuery?`Matching “${perfumeQuery}”${favoritesView?' in your favorites':selected.size?' and all selected notes':''}.`:favoritesView?'Your saved perfumes. Saved in this browser on this device.':selected.size?`${selected.size===1?'Containing your selected note':'Containing all '+selected.size+' selected notes'}.`:'All perfumes in the collection.';$('#cards').innerHTML=matches.length?matches.slice(page*size,(page+1)*size).map(p=>{const ids=[...p.notes].sort((a,b)=>Number(selected.has(b))-Number(selected.has(a)));return `<article class="card"><button class="bottle-button" data-perfume="${p.id}" aria-label="View bottle and notes for ${esc(p.name)} by ${esc(p.brand)}">${bottle(p)}</button><div class="card-main"><span class="brand">${esc(p.brand)}</span><div class="perfume-heading"><h3><button class="perfume-name" data-perfume="${p.id}" aria-label="View ${esc(p.name)} by ${esc(p.brand)}">${esc(p.name)}</button></h3>${favoriteButton(p)}</div><span class="metadata">${esc(title(p.gender||'Unspecified'))}${p.year?' · '+esc(p.year):''}</span><div class="rating"><span class="star" aria-hidden="true">★</span> ${p.rating?p.rating.toFixed(2):'Unrated'} <span class="votes">${p.votes?reviewLink(p,'('+fmt(p.votes)+')'):''}</span></div><div class="tags">${ids.slice(0,4).map(tag).join('')}${ids.length>4?`<span class="tag">+${ids.length-4}</span>`:''}${!ids.length?'<span class="tag">Notes unavailable</span>':''}</div></div><div class="card-bottom"><button class="text-button" data-perfume="${p.id}">View notes</button><span class="sample-label">Find samples</span><div class="sample-links">${sampleLinks(p)}</div></div></article>`}).join(''):perfumeQuery?'<div class="empty"><h3>No matching perfumes</h3><p>Try another perfume name or brand, or adjust your selected notes.</p><button class="text-button" data-clear-search>Clear search</button></div>':favoritesView?'<div class="empty"><h3>No favorites yet</h3><p>Tap the heart beside a perfume to save it here.</p><button class="text-button" data-browse>Browse perfumes</button></div>':'<div class="empty"><h3>No matching perfumes</h3><p>No perfumes in this collection contain all these notes.<br>Remove one of your selected notes to broaden the search.</p><button class="text-button" data-reset>Clear selected notes</button></div>';$('#page-label').textContent=matches.length?`${fmt(page*size+1)}–${fmt(Math.min((page+1)*size,matches.length))} of ${fmt(matches.length)}`:'No matches';$('#prev').disabled=page===0;$('#next').disabled=(page+1)*size>=matches.length}

function noteButton(id){const group=data.notes[id].group??id;return `<button class="tag note-link ${selected.has(group)?'match':''}" data-explore-note="${group}" aria-label="Find perfumes with ${esc(title(data.notes[group].name))}">${esc(title(data.notes[id].name))}</button>`}
const similarCache=new Map();
function similarPerfumes(p){
 if(similarCache.has(p.id))return similarCache.get(p.id);
 const notes=new Set(p.notes),identity=searchKey(p.brand+' '+p.name);
 if(!notes.size)return [];
 const ranked=[];
 for(const candidate of data.perfumes){
  if(candidate.id===p.id||!candidate.notes.length||searchKey(candidate.brand+' '+candidate.name)===identity)continue;
  const shared=candidate.notes.filter(id=>notes.has(id));
  if(shared.length<Math.min(2,notes.size))continue;
  ranked.push({perfume:candidate,shared,score:shared.length/(notes.size+candidate.notes.length-shared.length)});
 }
 ranked.sort((a,b)=>b.score-a.score||b.shared.length-a.shared.length||b.perfume.votes-a.perfume.votes||a.perfume.id-b.perfume.id);
 const seen=new Set(),result=[];
 for(const match of ranked){const key=searchKey(match.perfume.brand+' '+match.perfume.name);if(seen.has(key))continue;seen.add(key);result.push(match);if(result.length===4)break}
 similarCache.set(p.id,result);return result;
}
function similarSection(p){const suggestions=similarPerfumes(p);return `<section class="similar-section" aria-label="Perfumes with similar notes"><h3>Similar notes, more perfumes</h3><p>Based on shared notes.</p>${suggestions.length?`<div class="similar-list">${suggestions.map(({perfume:q,shared})=>`<article class="similar-perfume"><button class="bottle-button" data-perfume="${q.id}" aria-label="View bottle and notes for ${esc(q.name)} by ${esc(q.brand)}">${bottle(q)}</button><div><span class="brand">${esc(q.brand)}</span><h4><button class="perfume-name" data-perfume="${q.id}" aria-label="View ${esc(q.name)} by ${esc(q.brand)}">${esc(q.name)}</button></h4><p>${fmt(shared.length)} shared ${shared.length===1?'note':'notes'}</p><div class="tags">${shared.slice(0,4).map(noteButton).join('')}${shared.length>4?`<span class="tag">+${shared.length-4}</span>`:''}</div></div></article>`).join('')}</div>`:`<p>${p.notes.length?'No close note matches found.':'Suggestions will appear when notes are available for this perfume.'}</p>`}</section>`}
function exploreNote(id){
 selected=new Set([id]);perfumeQuery='';query='';family='All notes';favoritesView=false;
 $('#perfume-search').value='';$('#note-search').value='';
 document.querySelectorAll('.family').forEach(b=>{const active=b.dataset.family===family;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});
 $('#detail').close();update();refreshFavorites();$('#notes').scrollTop=0;
 const heading=$('.results-top h2');heading.tabIndex=-1;heading.focus({preventScroll:true});$('.results').scrollIntoView({block:'start'});
}

function details(id){const p=data.perfumes[id];$('#detail-content').innerHTML=`${bottle(p,true)}<span class="brand">${esc(p.brand)}</span><div class="perfume-heading"><h2>${esc(p.name)}</h2>${favoriteButton(p)}</div><p>${esc(title(p.gender||'Unspecified'))}${p.year?' · '+esc(p.year):''} · ${p.rating?p.rating.toFixed(2)+' / 5':'Unrated'}${p.votes?' from '+reviewLink(p,fmt(p.votes)+' reviews'):''}</p>${(p.source==='luckyscent'?[]:p.layers).map((layer,i)=>(p.layers[3]?.length&&i<3)?'':`<h3>${['Top notes','Heart notes','Base notes','Fragrance notes · Stages not specified'][i]}</h3><div class="tags">${layer.length?[...layer].sort((a,b)=>data.notes[a].name.localeCompare(data.notes[b].name)).map(noteButton).join(''):'<span class="muted">Not listed in the dataset</span>'}</div>`).join('')}${p.luckyNotes?.length?`<h3>Luckyscent notes · Stages not specified</h3><div class="tags">${[...p.luckyNotes].sort((a,b)=>data.notes[a].name.localeCompare(data.notes[b].name)).map(noteButton).join('')}</div><p>${esc(p.luckySource)}${p.luckyUrl?` · <a href="${esc(p.luckyUrl)}" target="_blank" rel="noopener noreferrer">View source</a>`:''}</p>`:''}${p.noteSource?`<p><a href="${esc(p.noteSource)}" target="_blank" rel="noopener noreferrer">Note source</a> · Added ${esc(p.noteChecked)}</p>`:''}${p.source==='structured'?'':`<p>${p.source.startsWith('online-')?'Notes added from online research. Dataset matches are based on a unique perfume name and brand, with matching release years when available.':p.source==='luckyscent'?(p.luckyNotes?.length?'Notes from Luckyscent.':'Luckyscent does not list usable notes for this record.'):p.source==='description'?'Notes extracted from the supplied fragrance description.':(p.luckyNotes?.length?'Original dataset notes unavailable; Luckyscent notes are listed above.':'This record has no usable note list in the supplied files.')}</p>`}<section class="sample-section"><h3>Find samples</h3><div class="sample-links">${sampleLinks(p)}</div><p>${p.luckyUrl?'Direct product link; sample availability may change.':'Search results, not confirmed stock.'} Check the exact fragrance and concentration before ordering.</p></section><a class="outlink" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">View on ${p.source==='luckyscent'?'Luckyscent':'Fragrantica'}</a>${similarSection(p)}`;if(!$('#detail').open)$('#detail').showModal();$('#detail').scrollTop=0;$('.close').focus({preventScroll:true})}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.exploreNote!==undefined){exploreNote(Number(b.dataset.exploreNote));return}if(b.hasAttribute('data-clear-search')){perfumeQuery='';$('#perfume-search').value='';update();return}if(b.dataset.favorite!==undefined){toggleFavorite(Number(b.dataset.favorite));return}if(b.hasAttribute('data-browse')){favoritesView=false;update();refreshFavorites();return}if(b.dataset.note!==undefined){const id=Number(b.dataset.note);selected.has(id)?selected.delete(id):selected.add(id);update()}if(b.dataset.remove!==undefined){selected.delete(Number(b.dataset.remove));update()}if(b.dataset.family!==undefined){family=b.dataset.family;document.querySelectorAll('.family').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderNotes();$('#notes').scrollTop=0}if(b.dataset.perfume!==undefined)details(Number(b.dataset.perfume));if(b.id==='clear'||b.hasAttribute('data-reset')){selected.clear();update()}});
$('#perfume-search').addEventListener('input',e=>{perfumeQuery=e.target.value.trim();if(data)update()});
$('#note-search').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();renderNotes();$('#notes').scrollTop=0});$('#sort').addEventListener('change',e=>{sort=e.target.value;update()});for(const [id,step] of [['prev',-1],['next',1]])$('#'+id).onclick=()=>{page+=step;renderCards();$('.results').scrollIntoView({behavior:'smooth',block:'start'})};$('.close').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});$('#about').onclick=()=>{$('#detail-content').innerHTML=`<h2>about</h2><p>Hi Alex! I've been working on this for a few days now, but i spoiled it by accidentally bringing it up. whatever. just motivated me to finish it. All the data is pulled from Fragrantica and Luckyscent, so everything your little heart desires should be on here. the site has like 72k perfumes so go crazy. I love you to the point of invention :)</p>`;$('#detail').showModal()};
fetch('data.json?v=20260926-spirits').then(r=>{if(!r.ok)throw Error('Unable to load collection');return r.json()}).then(d=>{data=d;totalCounts=new Uint32Array(d.notes.length);data.perfumes.forEach((p,id)=>{p.id=id;p.favoriteKey=favoriteKey(p);p.searchText=searchKey(p.brand+' '+p.name);p.notes=[...new Set([...p.layers.flat(),...(p.luckyNotes||[])].map(id=>d.notes[id].group??id))];for(const note of p.notes)totalCounts[note]++});$('#total').textContent=fmt(d.stats.total);$('#note-total').textContent=fmt(d.notes.filter(visibleNote).length)+' notes';const families=['All notes',...new Set(d.notes.filter(visibleNote).map(n=>n.family))];families.sort((a,b)=>a==='All notes'?-1:b==='All notes'?1:a==='Other'?1:b==='Other'?-1:a.localeCompare(b));$('#families').innerHTML=families.map(f=>`<button class="family ${f===family?'active':''}" data-family="${esc(f)}" aria-pressed="${f===family}">${esc(f)}</button>`).join('');update();refreshFavorites();$('#favorites').disabled=false;$('#loading').hidden=true;$('#workspace').hidden=false}).catch(()=>{$('#loading').innerHTML='The collection could not be loaded. <button onclick="location.reload()">Try again</button>'});
